baseurl = "http://hugo.songlib.com/"
languageCode = "en-au"
metadataformat = "yaml"
pygmentsUseClasses = true
theme = "songlib"
title = "Songlib"
# [[menu.main]]
# name = "Home"
# url = "/"
# weight = 5
# [[menu.main]]
# name = "Documentation"
# url = "docs/"
# weight = 10
# identifier = "docs"
# [[menu.main]]
# name = "Chord-charts"
# url = "docs/chord-charts/"
# weight = 10
# identifier = "chord-charts"
# parent = "docs"
[params]
author = "Humphrey Murray"
copyright = "Released under my prefered license"
demo_site = "http://songlib.com/"
description = "a good description"
favicon = ""
permalink = "#"
provider = "GitHub"
repo_id = "myproject"
repo_url = "https://github.com/mynamemyproject"
version = "1.0.0"
[social]
github = "myname"
