baseurl = "http://hugo.songlib.com/"
languageCode = "en-au"
metadataformat = "yaml"
pygmentsUseClasses = true
theme = "hugo-darkdoc-theme"
title = "Songlib"
[[menu.main]]
name = "Documentation"
url = "docs/"
weight = 0
[params]
author = "Humphrey Murray"
copyright = "Released under my prefered license"
demo_site = "http://songlib.com/"
description = "a good description"
favicon = ""
permalink = "#"
provider = "GitHub"
repo_id = "myproject"
repo_url = "https://github.com/mynamemyproject"
version = "1.0.0"
[social]
github = "myname"
