name = "Songlib"
license = "MIT"
# licenselink = "https://github.com/adejoux/hugo-darkdoc-theme/blob/master/LICENSE.md"
# description = "bootstrap theme for documentation"
# homepage = "https://github.com/adejoux/hugo-darkdoc-theme"
tags = ["bootstrap", "documentation", "responsive"]
# features = ["", ""]
min_version = 0.15

[author]
  name = "Humphrey Murray"
  homepage = "https://humphrey.github.io"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
